### ISSUE TITLE
Handlebars hotspot page

### ISSUE THREAD

**Issue by Quintam26** [tospotamockingbird/tsam#16]
Create the basic handlebar template that will use the JSON api bird data. Next create the function that will compile the data in order to load it onto HTML page and somehow ping it onto our google map.

This would use the API bird data to show the types and number of birds within a given region to give user hotspot locations to visit.

**Comment by morristaylor** [comment]
Closing this. Using eBird API but not using Handlebars on this page since the data isn't what we initially expected (more location-based, less about bird attributes).
